Spawn:
  x:
  y:
  z:

# ------ Configs --------

allow-one-player-skip-night: true

#

# ------ Custom Item --------

beef-amount: 8

#

# ------ MESSAGES --------

# available prefix:
# - %player% - get the player name
#

join-msg: '&a&l Ciao &d&l%player%&a&l, ben ritornato nel server'

first-join-msg: '&a&l Ciao &d&l%player%&a&l, benvenuto nel server'

skip-msg: '&a&lThe Night Has Been Skipped By &d&l%player%'

#

#

#