name: SMPCore
version: '1.0-SNAPSHOT'
main: it.vincyxiroff.SMPCore.SMPCore
api-version: '1.21'
commands:
  feed:
    description: restore your food bar
    aliases:
      - food
      - refillfood
    usage: /feed [player]
    permission: smpcore.admin.feed
    permission-message: you need to have smpcore.admin.feed to use this command

  setspawn:
    description: let you set spawn
    aliases:
      - spawnset
    usage: /setspawn
    permission: smpcore.admin.setspawn

  spawn:
    description: makes you go to the spawn that has been set
    usage: /spawn
    permission: smpcore.spawn

  give-beef:
    description: Give beef to you or a specific player
    usage: /give-beef [player]
    permission: smpcore.admin.test.cmd1

  s-reload:
    description: reloads the configuration of the plugin
    usage: /s-reload
    permission: smpcore.admin.reload

  admin-gui:
    description: jus a admin gui
    usage: /admin-gui
    permission: smpcore.admin.gui-open

permission:
  smpcore.admin.*:
    description: GIVES YOU ALL THE ADMIN PERMS
    children:
      smpcore.admin.feed: true
      smpcore.admin.setspawn: true
      smpcore.spawn: true
      smpcore.admin.test.cmd1: true
      smpcore.admin.reload: true
      smpcore.admin.gui-open: true

  smpcore.admin.feed:
    description: give you permission to max your food bar

  smpcore.admin.setspawn:
    description: give you permission to set spawn

  smpcore.spawn:
    description: give you permission to go to the spawn

  smpcore.admin.test.cmd1:
    description: gives u access to secret test command

  smpcore.admin.reload:
    description: let you reload the plugin config

  smpcore.admin.gui-open:
    description: let you open the admin gui