Spawn:
  x:
  y:
  z:



# ------ Custom Item --------

beef-amount: 8


# ------ MESSAGES --------

# available prefix:
# - %player% - get the player name
#

join-msg: '&a&l Ciao &d&l%player%&a&l, ben ritornato nel server'

first-join-msg: '&a&l Ciao &d&l%player%&a&l, benvenuto nel server'

#

# ------ ADMIN GUI ITEMS GIVE --------

# how much beef?
beef-admin-gui: 16

#